### ISSUE TITLE
No Credentials

### ISSUE THREAD

**Issue by jschwarzwalder** [aws-samples/aws-modern-application-workshop#1]
In Module 2B, Step 1 Section C, I am instructed to enter the command:
```
docker push 111111111111.dkr.ecr.us-east-1.amazonaws.com/mythicalmysfits/service:latest
```
However, I get the error message: no basic auth credentials.

Also at the beginning of this module I am instructed to enter my account id, but there are no instructions for how to retrieve it. WIll users new to AWS know how to find this information?

```
docker build . -t {aws_account_id}.dkr.ecr.{us-east-1}.amazonaws.com/mythicalmysfits/service:latest
````

**Comment by abaird986** [comment]
Thank you for raising this! I've pushed in a change that instructs users to use STS to retrieve their account information. 

I've also replaced the instructions and command that should emphasize to new AWS users and future tutorial users that the image tag used when building their image should be the same one used when running/pushing the image.

You can see the commit [here](https://github.com/aws-samples/aws-modern-application-workshop/commit/fd2650e954177220c6e57a08b8f1f02d388a8941).

**Comment by jschwarzwalder** [comment]
I will try using STS to get my credentials, but I may still have an issue.

I had replaced the 111111 with my own account number retrieved from my console and the appropriate region.

I will test again and if I find issue will file a new issue.

**Comment by jschwarzwalder** [comment]
@abaird986  When I run  ```$(aws ecr get-login --no-include-email)```

This is returned:
```WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded```

Is that what I should get?

**Comment by abaird986** [comment]
Yep, that is correct.

**Comment by jschwarzwalder** [comment]
Next I get: 
```
docker push acount#.dkr.ecr.region.amazonaws.com/mythicalmysfits/service:latest
The push refers to repository [acountnumber.dkr.ecr.region.amazonaws.com/mythicalmysfits/service]
f23a55e1c618: Preparing 
7cb6307c97a8: Preparing 
0fa3653aefbd: Preparing 
322b6b80fba6: Preparing 
31edbee40763: Preparing 
374f3534200b: Preparing 
8fec0692e6a1: Preparing 
219d5a9f3bbe: Preparing 
67b9b2a215ea: Preparing 
956940650d5d: Preparing 
no basic auth credentials
```

**Comment by jschwarzwalder** [comment]
When I perform the following step
```
aws ecr describe-images --repository-name mythicalmysfits/service
```
my Image Details returns empty
```
{
    "imageDetails": []
}
```

@abaird986  Is this the expected result.

**Comment by abaird986** [comment]
No, that is not the expected result.  This indicates that the `ecr get-login` command you ran was likely executed for a different region than the ECR region you're looking to push the image into.

See more details to debug this here:
https://docs.aws.amazon.com/AmazonECR/latest/userguide/common-errors-docker.html#error-403

**Comment by vcik** [comment]
Hi @abaird986, @jschwarzwalder  ,
I'm still having issues with the 'no basic auth credentials'

My ImageDetails are empty.

Was this issue resolved?

**Comment by danielspangler** [comment]
If anyone else stumbles on this, check out this link:  For me, I had fat fingered my account id.  https://docs.aws.amazon.com/AmazonECR/latest/userguide/common-errors-docker.html
