### ISSUE TITLE
CodeBuild fails to execute a python command....

### ISSUE THREAD

**Issue by Niemetz** [aws-samples/aws-modern-application-workshop#234]
Module 4, step 3-A. 
CodeBuild failed to execute a python command:
![Screen Shot 2020-11-15 at 1 05 59 PM](https://user-images.githubusercontent.com/20528680/99192981-ee587a00-2743-11eb-8757-64aa8f96088d.png)
Please help take a look at this issue.
Thanks a lot!
John Nguyen
nguyen7744@yahoo.com

**Comment by moralesl** [comment]
In Ubuntu 20.04 there is no python-pip package anymore, only python3-pip.
Also the command is called pip3 not only pip

This issue is actually fixed in https://github.com/aws-samples/aws-modern-application-workshop/pull/244, 	https://github.com/aws-samples/aws-modern-application-workshop/pull/235, https://github.com/aws-samples/aws-modern-application-workshop/pull/223, https://github.com/aws-samples/aws-modern-application-workshop/pull/218, https://github.com/aws-samples/aws-modern-application-workshop/pull/212, https://github.com/aws-samples/aws-modern-application-workshop/pull/208 and https://github.com/aws-samples/aws-modern-application-workshop/pull/206.

**Comment by mskaggs2021** [comment]
The docker file for module 3 and 4 were still not using pip3 and python3-pip the build I cloned about a week ago (approximately feb 6, 2021). 

Also in Module 5, step 3 A - you're missing the command for adding the s3 bucket. It looks like you intended to have it there because the sentence ended with a ":".

**Comment by moabdelmoez** [comment]
Dockerfile on module 4 still did not updated to python3
